#!/usr/bin/python
# -*- coding: utf-8 

import os
import argparse
import sys


class color:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    EC = '\033[0m'


def create_module(p):

    p = p.strip('/')
    def cb(a, d, f):
        with open('%s/__init__.py' % d, 'w') as f:
            f.write('')
    try:
        os.makedirs(p)
        os.path.walk(p.split('/')[0], cb, None)
    except:
        print(color.FAIL + 'Error' + color.EC)
        sys.exit(1)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Creates a module.')
    parser.add_argument('path', metavar='P', type=str,
        help='Intended module path')
    args = parser.parse_args()
    print(color.OKBLUE + 'Creating module' + color.EC)
    create_module(args.path)
